### ISSUE TITLE
Kubevirt + Ubuntu Testing

### ISSUE THREAD

**Issue by apoorvemohan** [intel/kubevirt-tdx#9]
Has `kubevirt-tdx` been tested with Ubuntu-based K8 installation?

cc: @mengmeiye

**Comment by LeiZhou-97** [comment]
hi @apoorvemohan  [@mengmeiya](https://github.com/mengmeiye)

I updated the wiki about build section.(kubevirt-tdx doest not provide pre-built images) If mengmei wants to try the kubevirt-tdx, she can follow it. 

https://github.com/intel/kubevirt-tdx/wiki/0.-Getting-started

if meet any problems, feel free to pin me.

**Comment by mengmeiye** [comment]
Thanks @LeiZhou-97

**Comment by mengmeiye** [comment]
Thanks @LeiZhou-97 
I followed the steps but got the following error by describing the vmi:
```
  Normal   SuccessfulCreate  5m16s  virtualmachine-controller  Created virtual machine pod virt-launcher-vmi-ubuntu-td-c8zgv
  Warning  SyncFailed        5m11s  virt-handler               server error. command SyncVMI failed: "LibvirtError(Code=1, Domain=10, Message='internal error: QEMU unexpectedly closed the monitor (vm='default_vmi-ubuntu-td'): 2024-05-20T17:52:24.038084Z qemu-kvm: -accel kvm: vm-type tdx not supported by KVM')"
  Normal   Started           5m11s  virt-handler               VirtualMachineInstance started.
```

Looks like `qemu-kvm` inside of the pod doesn't support tdx... 

The yaml file I'm using is:
```yaml
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-ubuntu-td
  name: vmi-ubuntu-td
spec:
  domain:
    launchSecurity:
      tdx:
        QGS: vsock:2:4050
    clock:
      timer:
        hpet:
          present: false
    machine:
      type: q35
    cpu:
      model: host-passthrough
      sockets: 1
      cores: 4
    features:
      acpi: {}
      apic: {}
    devices:
      autoattachVSOCK: true
      autoattachGraphicsDevice: false
      disks:
      - disk:
          bus: virtio
        name: containerdisk
    firmware:
      bootloader:
        efi:
          secureBoot: false
    resources:
      requests:
        memory: 16Gi
  terminationGracePeriodSeconds: 10
  volumes:
  - containerDisk:
      image: localhost/guest-ubuntu-tdx:latest
    name: containerdisk
```
